### PR TITLE
Add .mobi version of Meanings

### PR DESCRIPTION
**Pull request by mattbeshara**
Hi there!  Thank you very much for publishing this collection and for making it available on GitHub as well, I'm sure many people will find this very useful.  As the person who has been putting together the ePub and Mobipocket version of the books published by Path Press Publications for a couple of years, I certainly appreciate the ePub version of the collected summarised transcripts.  I've opened this PR to add the the Mobipocket version of Meanings, which is necessary for Kindle users because (as far as I'm aware) Amazon don't let Kindles read ePubs.

This may be worth my creating a separate issue for, but would you consider creating a separate repo containing the unzipped source files for the ePub of the collected summarised transcripts?  Creating a Mobipocket file should be as straightforward as running the ePub file though Kindlegen (possibly available from your distro's package manager if you're on Linux, and from archive.org if not: https://archive.org/search.php?query=kindlegen&sin= ).  However, after attempting this with the ePub of the summarised transcripts, it appears there's a few issues which prevent the ePub being converted.  I'd be very happy to do the work to enable Kindlegen to process the ePub, if you're OK with either creating a repo with the source of the ePub yourself, or wouldn't mind me doing so.

Thanks again!

### CODE REVIEW

**Comment by BBBalls** [comment]
Hello,

Thank you for contributing to this project. I merged the .mobi file and added a link to it on the book page.

I have no problem with creating a separate repo for the html files use for transcriptions. Whatever expertise you want to contribute is welcome. When the new repo is created I will provide the link.

**Comment by BBBalls** [comment]
The repo is up with the HTML of _Collected Essays & Summarized Talk Transcriptions_. I had published a new version just before seeing your pull request, so I included both the new version and the version you downloaded already.

https://github.com/BBBalls/hillside_hermitage_essays_transcriptions

**Comment by BBBalls** [comment]
I was able to successfully generate a mobi version of the collected essays and transcriptions using KindleGen using the newer edition of the epub. It has been pushed to the archive, and is available for download.

Given your background with Path Press, you are very likely able to produce a better e-book than me. I just wanted to be able to read the essays on my Kobo reader, so I figured out a way to make an epub, without any prior knowledge. If you are at all inclined to work on the collection, it is welcome.

**Comment by mattbeshara** [comment]
Thank you!

I've just put a .mobi build of the newer version of the collected transcriptions onto a recent-ish Kindle (a Paperwhite 3 I think) and generally it looks very nice.  There are a few points I think could be improved upon in regard to the formatting of the content, and I'll open PRs for those in the new repo as I have the time.  But overall, in its current state, it's more readable than the average e-book.

The most significant suggestion I have at this stage is not to do with the formatting of the content itself though, but in how the repo is organised, and how the e-books are generated.  It will be easier in the long run to have the new repo consist only of the 'skeleton' of the ePub and a shell script which operates on the content of that repo to generate the e-books directly from the original Markdown files, rather than having to maintain multiple copies of the content.  If nothing else, it means that new content only has to be added in one place.

I have a setup similar to what I describe above that I've been using for a while to generate the e-books for PPP, and when I have time, I'll try to put together a variant of it for this e-book.

**Pull request merged**
